//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentApplication.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int Id { get; set; }
        public string CreditCardNumber { get; set; }
        public string CardHolder { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> SecurityCode { get; set; }
        public decimal Amount { get; set; }
        public string ServiceUsed { get; set; }
    }
}
